services:
  weather_backend:
    build: ./backend
    container_name: weather_backend
    ports:
      - "8001:8001"
    networks:
      - app_network

  nginx_proxy_2:
    image: nginx:alpine
    container_name: nginx_proxy_2
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - weather_backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
